import type { WeddingConfig } from "@/types/wedding";

/**
 * Couple and family details are taken from the families' biodata.
 * Venue addresses are kept separate and are not sourced from those documents.
 */
export const isSamplePreview = false;

export const wedding: WeddingConfig = {
  couple: {
    bride: {
      firstName: "Puspita",
      lastName: "Goswami",
      fullName: "Puspita Goswami",
      bengaliName: "পুষ্পিতা গোস্বামী",
      initial: "P",
      bengaliInitial: "প",
      parents: "Daughter of Jagadish Chandra Goswami and Aroti Goswami",
      shortBio:
        "From Goswami Bari in Sreemangal, Maulvibazar. She studied computer science and engineering at Leading University, Sylhet, completed an MSc in Cybersecurity at Northumbria University, and is reading for an MSc in Computer Science at the University of East London.",
      shortBioBn:
        "শ্রীমঙ্গল, মৌলভীবাজারের গোস্বামী বাড়ির মেয়ে। সিলেটে কম্পিউটার সায়েন্স পড়েছেন, নর্থামব্রিয়ায় সাইবারসিকিউরিটি এবং ইস্ট লন্ডন বিশ্ববিদ্যালয়ে কম্পিউটার সায়েন্সে স্নাতকোত্তর করছেন।",
    },
    groom: {
      firstName: "Gaurav",
      lastName: "Mazumdar",
      fullName: "Gaurav Mazumdar",
      bengaliName: "গৌরব মজুমদার",
      initial: "G",
      bengaliInitial: "গ",
      parents: "Son of Subhash Mazumdar and Savita Sarkar",
      shortBio:
        "From Janakpuri, Delhi. A full-stack developer, he studied at St. Martin's Diocesan School, completed his BCA and MCA in Delhi, and is reading for an MSc in Computer Science at the University of East London.",
      shortBioBn:
        "দিল্লির জনকপুরীর ছেলে। ফুল-স্ট্যাক ডেভেলপার। সেন্ট মার্টিনস স্কুলের পর দিল্লিতে বিসিএ ও এমসিএ এবং ইস্ট লন্ডন বিশ্ববিদ্যালয়ে কম্পিউটার সায়েন্সে স্নাতকোত্তর করছেন।",
    },
    nameOrder: "bride-first",
    monogram: { left: "P", right: "G", joiner: "x" },
  },
  date: {
    iso: "2026-11-26T16:00:00+00:00",
    display: "26 November 2026",
    displayBn: "২৬ নভেম্বর ২০২৬",
    time: "4:00 in the evening",
    timezone: "Europe/London",
  },
  location: {
    city: "Kolkata",
    cityBn: "কলকাতা",
    region: "West Bengal",
  },
  hero: {
    kicker: "Two families. Two stories. One beautiful beginning.",
    kickerBn: "দুটি পরিবার। দুটি গল্প। একটি সুন্দর সূচনা।",
    line: "A Bengali wedding, written by hand and opened by you.",
    lineBn: "একটি বাংলা শুভ বিবাহ, আপনার জন্য লেখা।",
  },
  saveTheDate: {
    line: "Please keep this evening for us.",
    lineBn: "এই সন্ধ্যাটি আমাদের জন্য রেখে দিন।",
  },
  storyIntro: {
    title: "Our Story",
    titleBn: "আমাদের গল্প",
    text: "It began on a DLR train, on the first day of university. It continues with two families learning how to become one.",
    textBn: "শুরু হয়েছিল বিশ্ববিদ্যালয়ের প্রথম দিনে, এক ডিএলআর ট্রেনে। এখন দুটি ঘর এক হওয়ার পথে।",
  },
  story: [
    {
      id: "met",
      year: "21st September 2025",
      title: "How We Met",
      titleBn: "যেখানে দেখা",
      text: "On 21 September 2025, his first day of university, Gaurav saw Puspita on the DLR. She was sitting with her phone; he was standing nearby. Before they had even met, he had developed a quiet crush. Later that morning, he saw her again in class. She was his classmate, and a friendship began.",
      textBn: "২১ সেপ্টেম্বর ২০২৫, বিশ্ববিদ্যালয়ের প্রথম দিন। ডিএলআর-এ পুষ্পিতা বসে ফোন দেখছিলেন; গৌরব কাছে দাঁড়িয়ে ছিলেন। দেখা হওয়ার আগেই এক নীরব ভালোলাগা শুরু। সেই সকালেই ক্লাসে আবার দেখা - সহপাঠী। সেখান থেকেই বন্ধুত্ব।",
      photo: "/photos/journey/how-we-met.jpeg",
      photoAlt: "How Gaurav and Puspita met",
    },
    {
      id: "conversation",
      year: "29th September 2025",
      title: "Our First Conversation",
      titleBn: "প্রথম কথা",
      text: "In their first lecture, Puspita sat near the front, in the second row. Gaurav took a seat beside her, with one empty chair between them and his friends to his right. When the lecturer asked everyone to greet the people around them, he turned towards her just as she looked the other way. They laughed at their mistimed glance. When they turned again, their eyes met. They introduced themselves and spoke for the first time.",
      textBn: "প্রথম লেকচারে পুষ্পিতা সামনের দিকে, দ্বিতীয় সারিতে বসলেন। গৌরব পাশে বসলেন - মাঝে একটা খালি চেয়ার, ডানদিকে বন্ধুরা। লেকচারার যখন আশেপাশের সঙ্গে অভিবাদন জানাতে বললেন, তিনি তাঁর দিকে তাকালেন, তিনি অন্যদিকে। ভুল তাকানোয় হাসি। আবার তাকাতেই চোখে চোখ। পরিচয়, আর প্রথম কথা।",
      photo: "/photos/journey/first-conversation.jpeg",
      photoAlt: "Their first conversation",
    },
    {
      id: "trip",
      year: "17th December 2025",
      title: "Our First Trip",
      titleBn: "প্রথম যাত্রা",
      text: "Puspita invited Gaurav to Winter Wonderland and treated him to everything that day, from the rides to the food. They ate well, went on ride after ride, and had a wonderful time together.",
      textBn: "পুষ্পিতা গৌরবকে উইন্টার ওয়ান্ডারল্যান্ডে ডাকলেন, আর সেদিন সব খরচ তিনিই নিলেন - রাইড থেকে খাবার। ভালো করে খেলেন, একের পর এক রাইডে উঠলেন, আর দারুণ সময় কাটালেন।",
      photo: "/photos/journey/first-tour.jpeg",
      photoAlt: "Their first trip together",
    },
    {
      id: "proposal",
      year: "3rd February 2026",
      title: "The Proposal",
      titleBn: "প্রস্তাব",
      text: "In Feb, they visited Greenwich. By then, they both knew how they felt; they were only waiting for someone to say it first. Gaurav did. Calmly and thoughtfully, he told Puspita he loved her and said she could take all the time she needed. Three or four weeks later, she gave him her answer: yes.",
      textBn: "ফেব্রুয়ারিতে তাঁরা গ্রিনউইচে গেলেন। দুজনেই জানতেন কেমন অনুভব করছেন; শুধু কেউ আগে বলবেন, সেই অপেক্ষা। গৌরব বললেন। শান্ত ও ভেবেচিন্তে পুষ্পিতাকে জানালেন তিনি ভালোবাসেন, আর সময় নিয়ে ভাবতে বললেন। তিন-চার সপ্তাহ পরে উত্তর এল: হ্যাঁ।",
      photo: "/photos/middle.jpg",
      photoAlt: "The proposal in Greenwich",
    },
    {
      id: "now",
      year: "26 November 2026",
      title: "And Now",
      titleBn: "এবং এখন",
      text: "On 26 November 2026, Puspita and Gaurav will marry. Both families chose the date and have given the couple their heartfelt blessing. Two families from different countries will become one, bringing joy to their relatives and especially their parents. Puspita and Gaurav are cherishing every moment as they look forward to beginning their life together.",
      textBn: "২৬ নভেম্বর ২০২৬ পুষ্পিতা ও গৌরবের বিবাহ। তারিখ দুই পরিবার ঠিক করেছেন, আন্তরিক আশীর্বাদ দিয়েছেন। দুই দেশের দুই পরিবার এক হবে - আত্মীয়দের আনন্দ, বিশেষ করে পিতা-মাতার। পুষ্পিতা ও গৌরব প্রতিটি মুহূর্ত উপভোগ করছেন, একসঙ্গে নতুন জীবনের অপেক্ষায়।",
      photo: "/photos/journey/and-now.png",
      photoAlt: "Puspita and Gaurav",
    },

  ],
  traditions: {
    kicker: "A Bengali wedding",
    kickerBn: "একটি বাংলা শুভ বিবাহ",
    title: "Written in ritual",
    titleBn: "আলপনায় লেখা",
    intro:
      "Two houses meet in rice, turmeric, sindoor and song: Goswami Bari of Sreemangal, and the Mazumdars of Delhi. These are the signs and rites that will hold Puspita and Gaurav as they marry.",
    introBn:
      "শ্রীমঙ্গলের গোস্বামী বাড়ি আর দিল্লির মজুমদার পরিবার মিলবে ধান, হলুদ, সিঁদুর আর গানে। পুষ্পিতা ও গৌরবের বিবাহ এই চিহ্ন ও রীতির মধ্যেই ধরা থাকবে।",
    rites: [
      {
        id: "aiburo-bhaat",
        title: "Aiburo Bhaat",
        titleBn: "আইবুড়ো ভাত",
        line: "The last meal in the natal home as an unmarried daughter or son, shared with the people who raised them.",
        lineBn: "বিয়ের আগে নিজের ঘরে শেষ ভোজন, যাঁরা বড় করেছেন তাঁদের সঙ্গে।",
      },
      {
        id: "gaye-holud",
        title: "Gaye Holud",
        titleBn: "গায়ে হলুদ",
        line: "Turmeric and marigold from both houses, smeared in blessing until the courtyard turns gold.",
        lineBn: "দুই ঘরের হলুদ ও গাঁদা, আশীর্বাদে আঙ্গিনা সোনা হয়ে ওঠে।",
      },
      {
        id: "ashirbaad",
        title: "Ashirbaad",
        titleBn: "আশীর্বাদ",
        line: "Elders bless the couple with paddy, durva grass and a touch of gold.",
        lineBn: "গুরুজনেরা ধান, দূর্বা আর সোনা দিয়ে আশীর্বাদ করেন।",
      },
      {
        id: "subho-drishti",
        title: "Subho Drishti",
        titleBn: "শুভ দৃষ্টি",
        line: "The first blessed gaze at the mandap, often through betel leaves, when the dhaak is loudest.",
        lineBn: "মণ্ডপে প্রথম শুভ দৃষ্টি, প্রায়ই পানের পাতায়, ঢাকের মাঝে।",
      },
      {
        id: "mala-badal",
        title: "Mala Badal",
        titleBn: "মালা বদল",
        line: "Garlands of tuberose and marigold exchanged as the first public promise.",
        lineBn: "রজনীগন্ধা ও গাঁদার মালা বদল, প্রথম প্রকাশ্য প্রতিশ্রুতি।",
      },
      {
        id: "saat-paak",
        title: "Saat Paak",
        titleBn: "সাত পাক",
        line: "The bride, carried on a pidi, circles the groom seven times before they sit as one.",
        lineBn: "কনে পিঁড়িতে চড়ে বরকে সাতবার প্রদক্ষিণ করেন।",
      },
      {
        id: "sindoor-daan",
        title: "Sindoor Daan",
        titleBn: "সিঁদুর দান",
        line: "Vermillion in the hair parting, the quiet moment the marriage is sealed.",
        lineBn: "সিঁথিতে সিঁদুর, যে নিঃশব্দ মুহূর্তে বিবাহ সম্পন্ন হয়।",
      },
      {
        id: "bou-bhaat",
        title: "Bou Bhaat",
        titleBn: "বৌ ভাত",
        line: "The bride's first meal in her new house, and the feast that welcomes both families as one.",
        lineBn: "নতুন ঘরে কনের প্রথম ভোজন, দুই পরিবারের মিলনের ভোজ।",
      },
    ],
  },
  events: [
    {
      id: "aiburo-bhaat",
      enabled: true,
      name: "Aiburo Bhaat",
      nameBn: "আইবুড়ো ভাত",
      date: "21 January 2027",
      dateIso: "2027-01-21T12:00:00+05:30",
      time: "12:30 in the afternoon",
      venueId: "bride-home",
      dressCode: "Soft ivory and festive cotton",
      dressCodeBn: "হালকা উৎসবের পোশাক",
      description: "A quiet lunch in the Goswami house. Come hungry. Leave with sweets.",
      descriptionBn: "গোস্বামী বাড়িতে একটি শান্ত দুপুরের ভোজন।",
      photograph: "/photos/event-aiburo.png",
      atmosphere: "ivory",
      mapLink: "https://maps.google.com/?q=Shyambazar,+Kolkata",
    },
    {
      id: "ashirbaad",
      enabled: true,
      name: "Ashirbaad",
      nameBn: "আশীর্বাদ",
      date: "22 January 2027",
      dateIso: "2027-01-22T11:00:00+05:30",
      time: "11:00 in the morning",
      venueId: "groom-home",
      dressCode: "Traditional, family colours",
      dressCodeBn: "পারিবারিক সাজ",
      description: "Elders from both houses bless the couple with rice, durva and gold.",
      descriptionBn: "দুই ঘরের গুরুজনের আশীর্বাদ।",
      photograph: "/photos/event-ashirbaad.png",
      atmosphere: "ivory",
      mapLink: "https://maps.google.com/?q=Bhowanipore,+Kolkata",
    },
    {
      id: "mehendi",
      enabled: true,
      name: "Mehendi",
      nameBn: "মেহেন্দি",
      date: "22 January 2027",
      dateIso: "2027-01-22T16:00:00+05:30",
      time: "4:00 in the afternoon",
      venueId: "bride-home",
      dressCode: "Greens, florals, easy festive wear",
      dressCodeBn: "সবুজ ও ফুলের রং",
      description: "Henna in the courtyard until the light goes. Music, tea, and stained palms.",
      descriptionBn: "আঙ্গিনায় মেহেন্দি, গান ও চা।",
      photograph: "/photos/event-mehendi.png",
      atmosphere: "marigold",
      mapLink: "https://maps.google.com/?q=Shyambazar,+Kolkata",
    },
    {
      id: "haldi",
      enabled: true,
      name: "Gaye Holud",
      nameBn: "গায়ে হলুদ",
      date: "23 January 2027",
      dateIso: "2027-01-23T10:00:00+05:30",
      time: "10:00 in the morning",
      venueId: "courtyard",
      dressCode: "Shades of yellow / traditional",
      dressCodeBn: "হলুদের রং / সাবেকি সাজ",
      description: "Turmeric, marigold and a little chaos. Wear something you do not mind staining.",
      descriptionBn: "হলুদ, গাঁদা আর একটু হৈচৈ।",
      photograph: "/photos/event-haldi.png",
      atmosphere: "marigold",
      mapLink: "https://maps.google.com/?q=Shyambazar,+Kolkata",
    },
    {
      id: "sangeet",
      enabled: true,
      name: "Sangeet",
      nameBn: "সঙ্গীত সন্ধ্যা",
      date: "23 January 2027",
      dateIso: "2027-01-23T19:00:00+05:30",
      time: "7:00 in the evening",
      venueId: "banquet",
      dressCode: "Festive evening, jewel tones",
      dressCodeBn: "উৎসবের সন্ধ্যার সাজ",
      description: "Both families have rehearsed. Neither is ready. Come and sing anyway.",
      descriptionBn: "দুই ঘর গেয়ে উঠবে। আপনারাও গাইবেন।",
      photograph: "/photos/event-sangeet.png",
      atmosphere: "festive",
      mapLink: "https://maps.google.com/?q=Alipore,+Kolkata",
    },
    {
      id: "wedding",
      enabled: true,
      name: "Wedding Ceremony",
      nameBn: "শুভ বিবাহ",
      date: "26 November 2026",
      dateIso: "2026-11-26T16:00:00+00:00",
      time: "4:00 in the evening",
      venueId: "mandap",
      dressCode: "Bengali traditional / ivory and red",
      dressCodeBn: "বাংলা সাবেকি / সাদা-লাল",
      description: "Bor jatri at four. Please be seated before the shehnai begins.",
      descriptionBn: "চারটায় বরযাত্রী। শেহনাইয়ের আগে বসবেন।",
      photograph: "/photos/event-wedding.png",
      atmosphere: "ceremonial",
      mapLink: "https://maps.google.com/?q=Alipore,+Kolkata",
    },
    {
      id: "reception",
      enabled: true,
      name: "Reception / Bou Bhaat",
      nameBn: "বৌ ভাত / রিসেপশন",
      date: "27 November 2026",
      dateIso: "2026-11-27T19:00:00+00:00",
      time: "7:00 in the evening",
      venueId: "banquet",
      dressCode: "Evening formal, deep colours",
      dressCodeBn: "সন্ধ্যার আনুষ্ঠানিক সাজ",
      description: "Dinner, speeches, and the bride's first meal in her new house.",
      descriptionBn: "নতুন ঘরে প্রথম ভোজন, রাতের খাবার ও কথা।",
      photograph: "/photos/event-reception.png",
      atmosphere: "candlelight",
      mapLink: "https://maps.google.com/?q=Alipore,+Kolkata",
    },
  ],
  venues: [
    {
      id: "bride-home",
      name: "Goswami Bari",
      address: "14, Shyampukur Street, Shyambazar, Kolkata 700004",
      eventIds: ["aiburo-bhaat", "mehendi"],
      landmark: "A short walk from Shyambazar five-point crossing",
      parking: "Street parking on the lane; a car can stop at the gate",
      travelNotes: "The yellow house with the mango tree. Ring twice.",
      mapLink: "https://maps.google.com/?q=Shyampukur+Street,+Kolkata",
      illustration: "/photos/event-aiburo.png",
    },
    {
      id: "groom-home",
      name: "Mazumdar Bari",
      address: "8, Harish Mukherjee Road, Bhowanipore, Kolkata 700025",
      eventIds: ["ashirbaad"],
      landmark: "Near Jatin Das Park",
      parking: "A small courtyard can take four cars",
      travelNotes: "Enter through the green wooden door.",
      mapLink: "https://maps.google.com/?q=Harish+Mukherjee+Road,+Kolkata",
      illustration: "/photos/event-ashirbaad.png",
    },
    {
      id: "courtyard",
      name: "The Courtyard, Goswami Bari",
      address: "14, Shyampukur Street, Shyambazar, Kolkata 700004",
      eventIds: ["haldi"],
      landmark: "Same house as Aiburo Bhaat",
      parking: "Street parking on the lane",
      travelNotes: "Holud will stain. Wear yellow.",
      mapLink: "https://maps.google.com/?q=Shyampukur+Street,+Kolkata",
      illustration: "/photos/event-haldi.png",
    },
    {
      id: "mandap",
      name: "The Mandap Lawn",
      address: "Alipore Road, Alipore, Kolkata 700027",
      eventIds: ["wedding"],
      landmark: "Opposite the National Library grounds",
      parking: "Valet from the south gate",
      travelNotes: "The ceremony is on the lawn. Seating from 3:30 pm.",
      mapLink: "https://maps.google.com/?q=Alipore+Road,+Kolkata",
      illustration: "/photos/venue-mandap.png",
    },
    {
      id: "banquet",
      name: "The River Room",
      address: "Alipore Road, Alipore, Kolkata 700027",
      eventIds: ["sangeet", "reception"],
      landmark: "Same estate as the mandap, indoor hall",
      parking: "Valet from the south gate",
      travelNotes: "Dinner is seated. Tell us if you need a ride from the station.",
      mapLink: "https://maps.google.com/?q=Alipore+Road,+Kolkata",
      illustration: "/photos/event-reception.png",
    },
  ],
  travel: {
    enabled: true,
    airport: {
      name: "Netaji Subhas Chandra Bose International (CCU)",
      detail: "About 45 minutes to Alipore by car, longer in evening traffic.",
    },
    railway: {
      name: "Howrah / Sealdah",
      detail: "From Howrah, 35 minutes by car to Alipore. From Sealdah, about 25.",
    },
    hotel: {
      name: "The Alipore Rooms (sample block)",
      detail: "A small block is held until 10 January 2027.",
      bookingNote: "Mention Goswami-Mazumdar when you write.",
    },
    transport: "Cars can be arranged from the airport or Howrah if you tell us your arrival on the RSVP.",
    pickup: "A family car will wait at Gate 2 if you ask for pickup.",
    contactName: "Ishani Goswami",
    contactNumber: "+91 90000 00000",
  },
  families: {
    intro: "With the blessings of our families",
    introBn: "আমাদের পরিবারের আশীর্বাদে",
    brideHouse: "Goswami Bari, Sreemangal",
    brideHouseBn: "গোস্বামী বাড়ি, শ্রীমঙ্গল",
    groomHouse: "The Mazumdars of Delhi",
    groomHouseBn: "দিল্লির মজুমদার পরিবার",
    bride: [
      {
        name: "Jagadish Chandra Goswami",
        nameBn: "জগদীশ চন্দ্র গোস্বামী",
        relation: "Father",
        relationBn: "পিতা",
        note: "Retired head teacher, BTRI High School",
        noteBn: "অবসরপ্রাপ্ত প্রধান শিক্ষক, বিটিআরআই হাই স্কুল",
        circle: "parents",
      },
      {
        name: "Aroti Goswami",
        nameBn: "আরতি গোস্বামী",
        relation: "Mother",
        relationBn: "মাতা",
        note: "Homemaker",
        noteBn: "গৃহিণী",
        circle: "parents",
      },
      {
        name: "Purabi Goswami (Tonni)",
        nameBn: "পূরবী গোস্বামী (টনি)",
        relation: "Eldest sister",
        relationBn: "জ্যেষ্ঠা ভগ্নী",
        note: "Married to Ashish Bhattacharjee. Two children. Manitoba, Canada.",
        noteBn: "আশিষ ভট্টাচার্যের সহধর্মিণী। দুই সন্তান। ম্যানিটোবা, কানাডা।",
        circle: "siblings",
      },
      {
        name: "Jagajyoti Goswami (Jhaiok)",
        nameBn: "জগজ্যোতি গোস্বামী (ঝাইক)",
        relation: "Elder brother",
        relationBn: "জ্যেষ্ঠ ভ্রাতা",
        note: "Accountant. Married to Susmita Bhattacharjee. Two children. Dartford, UK.",
        noteBn: "হিসাবরক্ষক। সুস্মিতা ভট্টাচার্যের স্বামী। দুই সন্তান। ডার্টফোর্ড, যুক্তরাজ্য।",
        circle: "siblings",
      },
      {
        name: "Purnima Goswami (Tui)",
        nameBn: "পূর্ণিমা গোস্বামী (টুই)",
        relation: "Elder sister",
        relationBn: "জ্যেষ্ঠা ভগ্নী",
        note: "Married to Saikat Mukherjee. Two children. California, USA.",
        noteBn: "সৈকত মুখার্জির সহধর্মিণী। দুই সন্তান। ক্যালিফোর্নিয়া, যুক্তরাষ্ট্র।",
        circle: "siblings",
      },
      {
        name: "Joydev Goswami",
        nameBn: "জয়দেব গোস্বামী",
        relation: "Elder brother",
        relationBn: "জ্যেষ্ঠ ভ্রাতা",
        note: "Bank officer. Married to Gitosree Chakraborty. One child. Sylhet, Bangladesh.",
        noteBn: "ব্যাংক কর্মকর্তা। গীতশ্রী চক্রবর্তীর স্বামী। এক সন্তান। সিলেট, বাংলাদেশ।",
        circle: "siblings",
      },
      {
        name: "Himanshu Goswami",
        nameBn: "হিমাংশু গোস্বামী",
        relation: "Maternal uncle",
        relationBn: "মামা",
        note: "United Kingdom",
        noteBn: "যুক্তরাজ্য",
        circle: "elders",
      },
      {
        name: "Hiranmoy Goswami",
        nameBn: "হিরণ্ময় গোস্বামী",
        relation: "Maternal uncle",
        relationBn: "মামা",
        note: "United Kingdom",
        noteBn: "যুক্তরাজ্য",
        circle: "elders",
      },
      {
        name: "Himadri Goswami",
        nameBn: "হিমাদ্রি গোস্বামী",
        relation: "Maternal uncle",
        relationBn: "মামা",
        note: "Bangladesh",
        noteBn: "বাংলাদেশ",
        circle: "elders",
      },
    ],
    groom: [
      {
        name: "Subhash Mazumdar",
        nameBn: "সুভাষ মজুমদার",
        relation: "Father",
        relationBn: "পিতা",
        note: "Formerly in business",
        noteBn: "প্রাক্তন ব্যবসায়ী",
        circle: "parents",
      },
      {
        name: "Savita Sarkar",
        nameBn: "সবিতা সরকার",
        relation: "Mother",
        relationBn: "মাতা",
        note: "Retired Delhi Police, Sub-inspector",
        noteBn: "অবসরপ্রাপ্ত দিল্লি পুলিশ, সাব-ইন্সপেক্টর",
        circle: "parents",
      },
      {
        name: "Deepti Mazumdar",
        nameBn: "দীপ্তি মজুমদার",
        relation: "Elder sister",
        relationBn: "জ্যেষ্ঠা ভগ্নী",
        note: "Nursing at the Royal Free Hospital, London",
        noteBn: "রয়েল ফ্রি হাসপাতাল, লন্ডন। নার্সিং।",
        circle: "siblings",
      },
      {
        name: "Sanjeeb Chandra Mazumdar",
        nameBn: "সঞ্জীব চন্দ্র মজুমদার",
        relation: "Paternal uncle",
        relationBn: "পিতৃব্য",
        note: "Bardhaman",
        noteBn: "বর্ধমান",
        circle: "elders",
      },
      {
        name: "Sujit Mazumdar",
        nameBn: "সুজিত মজুমদার",
        relation: "Paternal uncle",
        relationBn: "পিতৃব্য",
        note: "Guskara",
        noteBn: "গুস্কারা",
        circle: "elders",
      },
      {
        name: "Prafulla Ranjan Chandra Mazumdar",
        nameBn: "প্রফুল্ল রঞ্জন চন্দ্র মজুমদার",
        relation: "Paternal uncle",
        relationBn: "পিতৃব্য",
        note: "Bardhaman",
        noteBn: "বর্ধমান",
        circle: "elders",
      },
      {
        name: "Dulal Chandra Mazumdar",
        nameBn: "দুলাল চন্দ্র মজুমদার",
        relation: "Paternal uncle",
        relationBn: "পিতৃব্য",
        note: "Guskara",
        noteBn: "গুস্কারা",
        circle: "elders",
      },
    ],
  },
  personalNote: {
    from: "Puspita & Gaurav",
    text: "We have shared so many chapters of our lives with the people we love. It would mean the world to begin this next one with you beside us.",
    textBn:
      "আমাদের এই নতুন পথচলার শুরুতে আপনাদের আশীর্বাদ ও উপস্থিতিই আমাদের সবচেয়ে বড় আনন্দ।",
    video: "",
  },
  quote: {
    text: "It began on a DLR train, on the first day of university. It continues with two families learning how to become one.",
    textBn: "শুরু হয়েছিল বিশ্ববিদ্যালয়ের প্রথম দিনে, এক ডিএলআর ট্রেনে। এখন দুটি ঘর এক হওয়ার পথে।",
  },
  countdown: {
    before: "Until forever begins",
    beforeBn: "চিরকাল শুরু হওয়ার আগে",
    after: "We are married. Thank you for walking with us.",
    afterBn: "আমরা পরিণয়সূত্রে আবদ্ধ। ধন্যবাদ।",
  },
  finale: {
    line: "See you there.",
    lineBn: "শুভ পরিণয়",
  },
  photos: {
    hero: "/photos/hero.png",
    story1: "/photos/right.jpg",
    story2: "/photos/right_side.jpg",
    childhood: "/photos/gallery-02.png",
    couplePortrait: "/photos/middle.jpg",
    finale: "/photos/finale.png",
    groomPortrait: "/photos/gaurav/groom-02.jpeg",
    bridePortrait: "/photos/puspita/bride-00.jpeg",
    groomSlideshow: [
      "/photos/gaurav/groom-02.jpeg",
      "/photos/gaurav/groom-00.jpeg",
      "/photos/gaurav/groom-01.jpeg",
      "/photos/gaurav/groom-03.jpeg",
      "/photos/gaurav/groom-04.jpeg",
      "/photos/gaurav/groom-05.jpeg",
      "/photos/gaurav/groom-06.jpeg",
    ],
    brideSlideshow: [
      "/photos/puspita/bride-00.jpeg",
      "/photos/puspita/bride-01.jpeg",
      "/photos/puspita/bride-02.jpeg",
      "/photos/puspita/bride-03.jpeg",
      "/photos/puspita/bride-04.jpeg",
      "/photos/puspita/bride-05.jpeg",
      "/photos/puspita/bride-06.jpeg",
    ],
    preWedding: [
      "/photos/couple.png",
      "/photos/story-trip.png",
      "/photos/story-met.png",
      "/photos/gallery-01.png",
    ],
    gallery: [
      { src: "/photos/gallery-01.png", caption: "Jasmine, the morning of holud", captionBn: "গায়ে হলুদের সকাল", date: "2026" },
      { src: "/photos/gallery-02.png", caption: "Alpana at dawn", captionBn: "ভোরের আলপনা", date: "2026" },
      { src: "/photos/gallery-03.png", caption: "College Street, again", captionBn: "আবার কলেজ স্ট্রিট", date: "2025" },
      { src: "/photos/hero.png", caption: "The courtyard", captionBn: "আঙ্গিনা", date: "2026" },
      { src: "/photos/bride.png", caption: "Puspita", captionBn: "পুষ্পিতা", date: "2026" },
      { src: "/photos/groom.png", caption: "Gaurav", captionBn: "গৌরব", date: "2026" },
      { src: "/photos/story-trip.png", caption: "The winter train", captionBn: "শীতের ট্রেন", date: "2022" },
      { src: "/photos/finale.png", caption: "After the lamps", captionBn: "প্রদীপের পরে", date: "2026" },
    ],
  },
  music: {
    src: "/music/ambiance.mp3",
    youtubeId: "-2w18bd-ZQ4",
    title: "Wedding song",
  },
  contacts: [
    { name: "Ishani Goswami", role: "Family", phone: "+91 90000 00000" },
    { name: "Arindam Mazumdar", role: "Wedding desk", phone: "+91 90000 00001" },
  ],
  social: {
    title: "Puspita & Gaurav",
    description: "A Bengali wedding in Kolkata",
    descriptionBn: "আপনাকে আমাদের শুভ বিবাহে সাদর আমন্ত্রণ",
    image: "/og.jpg",
    siteUrl: "https://example.com",
  },
  rsvp: {
    acceptLabel: "Joyfully",
    maybeLabel: "Maybe",
    declineLabel: "Can't",
    thanks: "We can't wait to celebrate with you.",
    thanksBn: "ধন্যবাদ",
    maybeThanks: "Thank you. We will keep you close as plans settle.",
    maybeThanksBn: "ধন্যবাদ। খবর রাখব।",
    declineThanks: "You will be missed, and held close.",
    declineThanksBn: "আপনাদের অভাব অনুভব করব।",
    byline: "Please respond by 12 November 2026",
    hashtag: "#PUSPITAWEDSGAURAV",
  },
  copy: {
    openInvitation: "Open Invitation",
    openInvitationBn: "আমন্ত্রণ খুলুন",
    invitationFor: "An invitation for",
    invitationForBn: "আমন্ত্রণ",
    dearGuest: "Dear Guest",
    shubhoBibaho: "শুভ বিবাহ",
    twoHearts: "দুটি হৃদয়, একটি পথ",
    comeCelebrate: "এসো, আমাদের আনন্দের সঙ্গী হও",
    ourStory: "Our Story",
    ourStoryBn: "আমাদের গল্প",
    traditions: "Traditions",
    traditionsBn: "ঐতিহ্য",
    events: "Events",
    eventsBn: "অনুষ্ঠান",
    gallery: "Gallery",
    galleryBn: "ছবি",
    venue: "Venue",
    venueBn: "স্থান",
    rsvp: "RSVP",
    untilSubhoDrishti: "Until we say শুভ দৃষ্টি",
    seeYouThere: "See you there.",
    addToCalendar: "Add to Calendar",
    openMaps: "Open in Google Maps",
    preparing: "Preparing your invitation",
    preparingBn: "আপনার আমন্ত্রণ প্রস্তুত হচ্ছে",
  },
};

export function coupleNames(order: WeddingConfig["couple"]["nameOrder"] = wedding.couple.nameOrder) {
  const { bride, groom } = wedding.couple;
  return order === "bride-first"
    ? { first: bride, second: groom }
    : { first: groom, second: bride };
}

export function enabledEvents() {
  return wedding.events.filter((event) => event.enabled);
}

export function eventsForGuest(eventIds: string[]) {
  return enabledEvents().filter((event) => eventIds.includes(event.id));
}

export function venueById(id: string) {
  return wedding.venues.find((venue) => venue.id === id);
}
