import type { WeddingConfig } from "@/types/wedding";

/**
 * SAMPLE PREVIEW
 * This file is filled with a finished fictional couple so the design can be judged.
 * Replace every field with your real details before sending invitations.
 * Set isSamplePreview to false to hide the sample badge.
 */
export const isSamplePreview = true;

export const wedding: WeddingConfig = {
  couple: {
    bride: {
      firstName: "Ananya",
      lastName: "Sengupta",
      fullName: "Ananya Sengupta",
      bengaliName: "অনন্যা সেনগুপ্ত",
      initial: "A",
      bengaliInitial: "অ",
      parents: "Daughter of Debashish and Krishna Sengupta",
      shortBio:
        "An architect who still draws North Kolkata courtyards from memory. She takes her tea without sugar and never misses a Durga Puja at home.",
    },
    groom: {
      firstName: "Rohan",
      lastName: "Bose",
      fullName: "Rohan Bose",
      bengaliName: "রোহন বসু",
      initial: "R",
      bengaliInitial: "র",
      parents: "Son of Anirban and Malini Bose",
      shortBio:
        "A historian who cooks better than he admits. He proposed badly, in the rain, on the ghat, and she said yes before he finished the sentence.",
    },
    nameOrder: "bride-first",
    monogram: { left: "A", right: "R", joiner: "x" },
  },
  date: {
    iso: "2027-01-24T16:00:00+05:30",
    display: "24 January 2027",
    displayBn: "২৪ জানুয়ারি ২০২৭",
    time: "4:00 in the evening",
    timezone: "Asia/Kolkata",
  },
  location: {
    city: "Kolkata",
    cityBn: "কলকাতা",
    region: "West Bengal",
  },
  hero: {
    kicker: "Two families. Two stories. One beautiful beginning.",
    kickerBn: "দুটি পরিবার। দুটি গল্প। একটি সুন্দর সূচনা।",
    line: "A Bengali wedding, written by hand and opened by you.",
    lineBn: "একটি বাংলা শুভ বিবাহ, আপনার জন্য লেখা।",
  },
  saveTheDate: {
    line: "Please keep this evening for us.",
    lineBn: "এই সন্ধ্যাটি আমাদের জন্য রেখে দিন।",
  },
  storyIntro: {
    title: "Our Story",
    titleBn: "আমাদের গল্প",
    text: "It began with a wrong tram and a borrowed book. It continues with two houses learning how to become one.",
    textBn: "শুরু হয়েছিল এক ভুল ট্রাম আর এক ধার করা বই দিয়ে। এখন দুটি ঘর এক হওয়ার পথে।",
  },
  story: [
    {
      id: "met",
      year: "2019",
      title: "How We Met",
      titleBn: "যেখানে দেখা",
      text: "College Street, in the rain. She was looking for a book that had already been sold. He was holding the last copy and did not know it yet.",
      textBn: "কলেজ স্ট্রিটে বৃষ্টিতে। সেই বইটি আর দোকানে ছিল না, শুধু তাঁর হাতে ছিল।",
      photo: "/photos/story-met.png",
      photoAlt: "A Kolkata bookshop verandah in the rain",
    },
    {
      id: "conversation",
      year: "2019",
      title: "The First Conversation",
      titleBn: "প্রথম কথা",
      text: "They spoke for two hours over tea that went cold. The letter she later wrote him still sits in a drawer in Bose Bari.",
      textBn: "ঠান্ডা চায়ে দুঘণ্টা কথা। সেই চিঠি আজও বসু বাড়ির ড্রয়ারে আছে।",
      photo: "/photos/story-talk.png",
      photoAlt: "Tea and a handwritten letter",
    },
    {
      id: "trip",
      year: "2022",
      title: "Our First Trip",
      titleBn: "প্রথম যাত্রা",
      text: "A slow train out of Howrah, mustard fields, and a shared window. They have taken that route every winter since.",
      textBn: "হাওড়া থেকে এক ধীর ট্রেন, সরিষা ক্ষেত, আর এক জানালা।",
      photo: "/photos/story-trip.png",
      photoAlt: "A train window at dusk",
    },
    {
      id: "proposal",
      year: "2025",
      title: "The Proposal",
      titleBn: "প্রস্তাব",
      text: "On the ghat, after the lamps were lit. The ring box was damp. She laughed, then said yes.",
      textBn: "ঘাটে, প্রদীপ জ্বলবার পরে। সিন্দুকটি ভিজে ছিল। তিনি হেসে হ্যাঁ বললেন।",
      photo: "/photos/story-proposal.png",
      photoAlt: "A ring beside the river",
    },
    {
      id: "now",
      year: "2027",
      title: "And Now",
      titleBn: "এবং এখন",
      text: "The houses have met. The date is written. We want the people we love in the courtyard when the dhaak begins.",
      textBn: "ঘর দুটি মিলেছে। তারিখ লেখা। ঢাক বাজলে আপনারা যেন কাছে থাকেন।",
      photo: "/photos/couple.png",
      photoAlt: "Ananya and Rohan",
    },
  ],
  events: [
    {
      id: "aiburo-bhaat",
      enabled: true,
      name: "Aiburo Bhaat",
      nameBn: "আইবুড়ো ভাত",
      date: "21 January 2027",
      dateIso: "2027-01-21T12:00:00+05:30",
      time: "12:30 in the afternoon",
      venueId: "bride-home",
      dressCode: "Soft ivory and festive cotton",
      dressCodeBn: "হালকা উৎসবের পোশাক",
      description: "A quiet lunch in the Sengupta house. Come hungry. Leave with sweets.",
      descriptionBn: "সেনগুপ্ত বাড়িতে একটি শান্ত দুপুরের ভোজন।",
      photograph: "/photos/event-aiburo.png",
      atmosphere: "ivory",
      mapLink: "https://maps.google.com/?q=Shyambazar,+Kolkata",
    },
    {
      id: "ashirbaad",
      enabled: true,
      name: "Ashirbaad",
      nameBn: "আশীর্বাদ",
      date: "22 January 2027",
      dateIso: "2027-01-22T11:00:00+05:30",
      time: "11:00 in the morning",
      venueId: "groom-home",
      dressCode: "Traditional, family colours",
      dressCodeBn: "পারিবারিক সাজ",
      description: "Elders from both houses bless the couple with rice, durva and gold.",
      descriptionBn: "দুই ঘরের গুরুজনের আশীর্বাদ।",
      photograph: "/photos/event-ashirbaad.png",
      atmosphere: "ivory",
      mapLink: "https://maps.google.com/?q=Bhowanipore,+Kolkata",
    },
    {
      id: "mehendi",
      enabled: true,
      name: "Mehendi",
      nameBn: "মেহেন্দি",
      date: "22 January 2027",
      dateIso: "2027-01-22T16:00:00+05:30",
      time: "4:00 in the afternoon",
      venueId: "bride-home",
      dressCode: "Greens, florals, easy festive wear",
      dressCodeBn: "সবুজ ও ফুলের রং",
      description: "Henna in the courtyard until the light goes. Music, tea, and stained palms.",
      descriptionBn: "আঙ্গিনায় মেহেন্দি, গান ও চা।",
      photograph: "/photos/event-mehendi.png",
      atmosphere: "marigold",
      mapLink: "https://maps.google.com/?q=Shyambazar,+Kolkata",
    },
    {
      id: "haldi",
      enabled: true,
      name: "Gaye Holud",
      nameBn: "গায়ে হলুদ",
      date: "23 January 2027",
      dateIso: "2027-01-23T10:00:00+05:30",
      time: "10:00 in the morning",
      venueId: "courtyard",
      dressCode: "Shades of yellow / traditional",
      dressCodeBn: "হলুদের রং / সাবেকি সাজ",
      description: "Turmeric, marigold and a little chaos. Wear something you do not mind staining.",
      descriptionBn: "হলুদ, গাঁদা আর একটু হৈচৈ।",
      photograph: "/photos/event-haldi.png",
      atmosphere: "marigold",
      mapLink: "https://maps.google.com/?q=Shyambazar,+Kolkata",
    },
    {
      id: "sangeet",
      enabled: true,
      name: "Sangeet",
      nameBn: "সঙ্গীত সন্ধ্যা",
      date: "23 January 2027",
      dateIso: "2027-01-23T19:00:00+05:30",
      time: "7:00 in the evening",
      venueId: "banquet",
      dressCode: "Festive evening, jewel tones",
      dressCodeBn: "উৎসবের সন্ধ্যার সাজ",
      description: "Both families have rehearsed. Neither is ready. Come and sing anyway.",
      descriptionBn: "দুই ঘর গেয়ে উঠবে। আপনারাও গাইবেন।",
      photograph: "/photos/event-sangeet.png",
      atmosphere: "festive",
      mapLink: "https://maps.google.com/?q=Alipore,+Kolkata",
    },
    {
      id: "wedding",
      enabled: true,
      name: "Wedding Ceremony",
      nameBn: "শুভ বিবাহ",
      date: "24 January 2027",
      dateIso: "2027-01-24T16:00:00+05:30",
      time: "4:00 in the evening",
      venueId: "mandap",
      dressCode: "Bengali traditional / ivory and red",
      dressCodeBn: "বাংলা সাবেকি / সাদা-লাল",
      description: "Bor jatri at four. Please be seated before the shehnai begins.",
      descriptionBn: "চারটায় বরযাত্রী। শেহনাইয়ের আগে বসবেন।",
      photograph: "/photos/event-wedding.png",
      atmosphere: "ceremonial",
      mapLink: "https://maps.google.com/?q=Alipore,+Kolkata",
    },
    {
      id: "reception",
      enabled: true,
      name: "Reception / Bou Bhaat",
      nameBn: "বৌ ভাত / রিসেপশন",
      date: "25 January 2027",
      dateIso: "2027-01-25T19:00:00+05:30",
      time: "7:00 in the evening",
      venueId: "banquet",
      dressCode: "Evening formal, deep colours",
      dressCodeBn: "সন্ধ্যার আনুষ্ঠানিক সাজ",
      description: "Dinner, speeches, and the bride's first meal in her new house.",
      descriptionBn: "নতুন ঘরে প্রথম ভোজন, রাতের খাবার ও কথা।",
      photograph: "/photos/event-reception.png",
      atmosphere: "candlelight",
      mapLink: "https://maps.google.com/?q=Alipore,+Kolkata",
    },
  ],
  venues: [
    {
      id: "bride-home",
      name: "Sengupta Bari",
      address: "14, Shyampukur Street, Shyambazar, Kolkata 700004",
      eventIds: ["aiburo-bhaat", "mehendi"],
      landmark: "A short walk from Shyambazar five-point crossing",
      parking: "Street parking on the lane; a car can stop at the gate",
      travelNotes: "The yellow house with the mango tree. Ring twice.",
      mapLink: "https://maps.google.com/?q=Shyampukur+Street,+Kolkata",
      illustration: "/photos/event-aiburo.png",
    },
    {
      id: "groom-home",
      name: "Bose Bari",
      address: "8, Harish Mukherjee Road, Bhowanipore, Kolkata 700025",
      eventIds: ["ashirbaad"],
      landmark: "Near Jatin Das Park",
      parking: "A small courtyard can take four cars",
      travelNotes: "Enter through the green wooden door.",
      mapLink: "https://maps.google.com/?q=Harish+Mukherjee+Road,+Kolkata",
      illustration: "/photos/event-ashirbaad.png",
    },
    {
      id: "courtyard",
      name: "The Courtyard, Sengupta Bari",
      address: "14, Shyampukur Street, Shyambazar, Kolkata 700004",
      eventIds: ["haldi"],
      landmark: "Same house as Aiburo Bhaat",
      parking: "Street parking on the lane",
      travelNotes: "Holud will stain. Wear yellow.",
      mapLink: "https://maps.google.com/?q=Shyampukur+Street,+Kolkata",
      illustration: "/photos/event-haldi.png",
    },
    {
      id: "mandap",
      name: "The Mandap Lawn",
      address: "Alipore Road, Alipore, Kolkata 700027",
      eventIds: ["wedding"],
      landmark: "Opposite the National Library grounds",
      parking: "Valet from the south gate",
      travelNotes: "The ceremony is on the lawn. Seating from 3:30 pm.",
      mapLink: "https://maps.google.com/?q=Alipore+Road,+Kolkata",
      illustration: "/photos/venue-mandap.png",
    },
    {
      id: "banquet",
      name: "The River Room",
      address: "Alipore Road, Alipore, Kolkata 700027",
      eventIds: ["sangeet", "reception"],
      landmark: "Same estate as the mandap, indoor hall",
      parking: "Valet from the south gate",
      travelNotes: "Dinner is seated. Tell us if you need a ride from the station.",
      mapLink: "https://maps.google.com/?q=Alipore+Road,+Kolkata",
      illustration: "/photos/event-reception.png",
    },
  ],
  travel: {
    enabled: true,
    airport: {
      name: "Netaji Subhas Chandra Bose International (CCU)",
      detail: "About 45 minutes to Alipore by car, longer in evening traffic.",
    },
    railway: {
      name: "Howrah / Sealdah",
      detail: "From Howrah, 35 minutes by car to Alipore. From Sealdah, about 25.",
    },
    hotel: {
      name: "The Alipore Rooms (sample block)",
      detail: "A small block is held until 10 January 2027.",
      bookingNote: "Mention Sengupta-Bose when you write.",
    },
    transport: "Cars can be arranged from the airport or Howrah if you tell us your arrival on the RSVP.",
    pickup: "A family car will wait at Gate 2 if you ask for pickup.",
    contactName: "Ishani Sengupta",
    contactNumber: "+91 90000 00000",
  },
  families: {
    intro: "With the blessings of our families",
    introBn: "আমাদের পরিবারের আশীর্বাদে",
    bride: [
      { name: "Debashish Sengupta", relation: "Father", relationBn: "পিতা" },
      { name: "Krishna Sengupta", relation: "Mother", relationBn: "মাতা" },
    ],
    groom: [
      { name: "Anirban Bose", relation: "Father", relationBn: "পিতা" },
      { name: "Malini Bose", relation: "Mother", relationBn: "মাতা" },
    ],
  },
  personalNote: {
    from: "Ananya & Rohan",
    text: "We have shared so many chapters of our lives with the people we love. It would mean the world to begin this next one with you beside us.",
    textBn:
      "আমাদের এই নতুন পথচলার শুরুতে আপনাদের আশীর্বাদ ও উপস্থিতিই আমাদের সবচেয়ে বড় আনন্দ।",
    video: "",
  },
  quote: {
    text: "It began with a wrong tram and a borrowed book. It continues with two houses learning how to become one.",
    textBn: "শুরু হয়েছিল এক ভুল ট্রাম আর এক ধার করা বই দিয়ে। এখন দুটি ঘর এক হওয়ার পথে।",
  },
  countdown: {
    before: "Until forever begins",
    beforeBn: "চিরকাল শুরু হওয়ার আগে",
    after: "We are married. Thank you for walking with us.",
    afterBn: "আমরা পরিণয়সূত্রে আবদ্ধ। ধন্যবাদ।",
  },
  finale: {
    line: "See you there.",
    lineBn: "শুভ পরিণয়",
  },
  photos: {
    hero: "/photos/hero.png",
    story1: "/photos/bride.png",
    story2: "/photos/groom.png",
    childhood: "/photos/gallery-02.png",
    couplePortrait: "/photos/couple.png",
    finale: "/photos/finale.png",
    preWedding: [
      "/photos/couple.png",
      "/photos/story-trip.png",
      "/photos/story-met.png",
      "/photos/gallery-01.png",
    ],
    gallery: [
      { src: "/photos/gallery-01.png", caption: "Jasmine, the morning of holud", captionBn: "গায়ে হলুদের সকাল", date: "2026" },
      { src: "/photos/gallery-02.png", caption: "Alpana at dawn", captionBn: "ভোরের আলপনা", date: "2026" },
      { src: "/photos/gallery-03.png", caption: "College Street, again", captionBn: "আবার কলেজ স্ট্রিট", date: "2025" },
      { src: "/photos/hero.png", caption: "The courtyard", captionBn: "আঙ্গিনা", date: "2026" },
      { src: "/photos/bride.png", caption: "Ananya", captionBn: "অনন্যা", date: "2026" },
      { src: "/photos/groom.png", caption: "Rohan", captionBn: "রোহন", date: "2026" },
      { src: "/photos/story-trip.png", caption: "The winter train", captionBn: "শীতের ট্রেন", date: "2022" },
      { src: "/photos/finale.png", caption: "After the lamps", captionBn: "প্রদীপের পরে", date: "2026" },
    ],
  },
  music: {
    src: "/music/ambiance.mp3",
    title: "Wedding ambience",
  },
  contacts: [
    { name: "Ishani Sengupta", role: "Family", phone: "+91 90000 00000" },
    { name: "Arindam Bose", role: "Wedding desk", phone: "+91 90000 00001" },
  ],
  social: {
    title: "Ananya & Rohan",
    description: "A Bengali wedding in Kolkata",
    descriptionBn: "আপনাকে আমাদের শুভ বিবাহে সাদর আমন্ত্রণ",
    image: "/og.jpg",
    siteUrl: "https://example.com",
  },
  rsvp: {
    acceptLabel: "Joyfully",
    maybeLabel: "Maybe",
    declineLabel: "Can't",
    thanks: "We can't wait to celebrate with you.",
    thanksBn: "ধন্যবাদ",
    maybeThanks: "Thank you. We will keep you close as plans settle.",
    maybeThanksBn: "ধন্যবাদ। খবর রাখব।",
    declineThanks: "You will be missed, and held close.",
    declineThanksBn: "আপনাদের অভাব অনুভব করব।",
    byline: "Please respond by 12 November 2026",
    hashtag: "#ANANYAWEDSROHAN",
  },
  copy: {
    openInvitation: "Open Invitation",
    openInvitationBn: "আমন্ত্রণ খুলুন",
    invitationFor: "An invitation for",
    invitationForBn: "আমন্ত্রণ",
    dearGuest: "Dear Guest",
    shubhoBibaho: "শুভ বিবাহ",
    twoHearts: "দুটি হৃদয়, একটি পথ",
    comeCelebrate: "এসো, আমাদের আনন্দের সঙ্গী হও",
    ourStory: "Our Story",
    ourStoryBn: "আমাদের গল্প",
    events: "Events",
    eventsBn: "অনুষ্ঠান",
    gallery: "Gallery",
    galleryBn: "ছবি",
    venue: "Venue",
    venueBn: "স্থান",
    rsvp: "RSVP",
    untilSubhoDrishti: "Until we say শুভ দৃষ্টি",
    seeYouThere: "See you there.",
    addToCalendar: "Add to Calendar",
    openMaps: "Open in Google Maps",
    preparing: "Preparing your invitation",
    preparingBn: "আপনার আমন্ত্রণ প্রস্তুত হচ্ছে",
  },
};

export function coupleNames(order: WeddingConfig["couple"]["nameOrder"] = wedding.couple.nameOrder) {
  const { bride, groom } = wedding.couple;
  return order === "bride-first"
    ? { first: bride, second: groom }
    : { first: groom, second: bride };
}

export function enabledEvents() {
  return wedding.events.filter((event) => event.enabled);
}

export function eventsForGuest(eventIds: string[]) {
  return enabledEvents().filter((event) => eventIds.includes(event.id));
}

export function venueById(id: string) {
  return wedding.venues.find((venue) => venue.id === id);
}
